version: '3'

networks: 
    iot:
        driver: bridge

services: 
    database:
        image: postgres
        container_name: postgres
        hostname: postgres
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        expose:
            - '5432'
        ports: 
            - '5432:5432'
        networks: 
            - iot

    human-api:
        image: vaca/human-api
        container_name: human-api
        hostname: human-api
        restart: always
        expose:
            - '1883'
            - '5432'
            - '9001'
            - '9999'
        ports:
            - '9999:9999'
        depends_on: 
            - database
        networks: 
            - iot

    mqtt-broker:
        image: eclipse-mosquitto
        container_name: broker
        hostname: broker
        restart: always
        volumes: 
            - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
        expose: 
            - '1883'
            - '9001'
        ports: 
            - '1883:1883'
        networks: 
            - iot

    device-api:
        image: vaca/device-api
        container_name: device-api
        hostname: device-api
        restart: always
        expose: 
            - '1883'
            - '5432'
            - '9001'
        depends_on: 
            - database
            - mqtt-broker
        networks: 
            - iot

    virtual-device:
        image: vaca/virtual-device
        container_name: virtual-device
        hostname: virtual-device
        restart: always
        expose: 
            - '1883'
            - '9001'
        depends_on: 
            - mqtt-broker
        networks: 
            - iot