version: '3'

networks: 
    iot:
        driver: bridge

services: 
    database:
        image: postgres
        container_name: postgres
        hostname: postgres
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        expose:
            - '5432'
        ports: 
            - '5432:5432'
        networks: 
            - iot