version: '3'

networks: 
    iot:
        driver: bridge

services: 
    database:
        image: postgres
        container_name: postgres
        hostname: postgres
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        expose:
            - '5432'
        ports: 
            - '5432:5432'
        networks: 
            - iot

    human-api:
        image: vaca/human-api
        container_name: human-api
        hostname: human-api
        restart: always
        expose:
            - '5432'
            - '9999'
        ports:
            - '9999:9999'
        depends_on: 
            - database
        networks: 
            - iot